AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Metrics/LineLength:
  Enabled: false
  Max: 110
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 10
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact
Metrics/BlockLength:
  Enabled: false